#!/bin/bash

#SBATCH -J cg          # Job name
#SBATCH -o cg.%j.out   # stdout; %j expands to jobid
#SBATCH -e cg.%j.err   # stderr; skip to combine stdout and stderr
#SBATCH -p normal    # queue
#SBATCH -N 16              # Number of nodes, not cores (16 cores/node)
#SBATCH -n 256             # Total number of MPI tasks (if omitted, n=N)
#SBATCH -t 01:00:00       # max time

#SBATCH --mail-user=dtao001@ucr.edu
#SBATCH --mail-type=ALL

#SBATCH -A TG-EAR130035       # class project/account code;

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 0 0 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 0 1 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 0 2 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 0 3 2 1000 3999 1000000

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 0 0 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 0 1 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 0 2 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 0 3 2 200 799 1000000

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 1 0 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 1 1 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 1 2 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 1 3 2 1000 3999 1000000

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 1 0 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 1 1 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 1 2 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 1 3 2 200 799 1000000

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 2 0 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 2 1 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 2 2 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 2 3 2 1000 3999 1000000

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 2 0 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 2 1 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 2 2 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 2 3 2 200 799 1000000

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 3 0 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 3 1 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 3 2 2 1000 3999 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/pwtk -ksp_type cg 3 3 2 1000 3999 1000000

ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 3 0 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 3 1 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 3 2 2 200 799 1000000
ibrun ./cg_solver -f /home1/02882/dingwen/matrices/G3_circuit -ksp_type cg 3 3 2 200 799 1000000